x-base_service: &base_service
  build:
      context: ./
      dockerfile: ./Dockerfile
      target: "${APP_ENV}"
  privileged: true
  restart: unless-stopped
  ports:
    - '22:22'
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  volumes:
    - ./data:/data

services:
  auto-gpu: &automatic
    <<: *base_service
    profiles: ["auto-gpu"]
    environment:
      APP_ENV: ${APP_ENV}
      SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
      K4H_RELEASE: ${K4H_RELEASE}
      TORCH_GPU_SUPPORT: true

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      TORCH_GPU_SUPPORT: false
    