version: "3.7"

services:
  k4hep:
    build:
      context: ./
      dockerfile: ./k4h_main/Dockerfile
      target: "${APP_ENV}"
    privileged: true
    environment:
      - APP_ENV
      - SSH_PUBLIC_KEY
      - TORCH_GPU_SUPPORT
    restart: always
    ports:
      - '22:22'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./data:/nfs/dust/ilc/user/bliewert