name: Key4hep Setup Test
on: [push]

jobs:
  key4hep_setup_job:
    runs-on: ubuntu-latest
    name: Set up key4hep
    steps:
      # Checkout the repo
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}'

      - name: Hello world action step
        id: hello
        uses: ./.github/actions/k4-hep-env-test
        with:
          an-input: 'KEY4HEP-VERSION'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
