name: Key4hep Setup Test
on: [push]

jobs:
  clone-repo-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose build auto-cpu

      - name: Test output
        run: docker compose run auto-cpu --entrypoint "which Marlin"