name: Key4hep Setup Test
on: [push]

jobs:
  clone-repo-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout current repo
        uses: actions/checkout@v4

  key4hep-setup-job:
    runs-on: ubuntu-latest
    needs: clone-repo-job
    container:
      image: '../../Dockerfile'
      options: --privileged

    steps:
      # Use the output from the `hello` step
      - name: Get the output time
        run: (ls /.dockerenv && echo Found dockerenv && echo "$(ls /cvmfs)") || (echo No dockerenv)
