name: Key4hep Setup Test
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Set up key4hep
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/k4-hep-env-test@v2
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
